export const TRANSACTION_MAX_FILES = 1_000;
export const TRANSACTION_MAX_OPERATIONS = 1_000;
export const TRANSACTION_MAX_VALIDATION_CHECKS = 100;
export const TRANSACTION_MAX_DIAGNOSTICS = 100;
export const TRANSACTION_MAX_ARTIFACTS = 512;
export const TRANSACTION_MAX_APPLIED_FILES = TRANSACTION_MAX_FILES;
export const TRANSACTION_MAX_READ_DEPENDENCIES = 10_000;
export const TRANSACTION_MAX_MANIFEST_BYTES = 16_777_216;
